server:
  port: 0

spring:
  application:
    name: api-socket-io

management:
  endpoints:
    web:
      exposure:
        include: health,info
        basePath: /actuator

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-host:http://localhost:8761/eureka/}