name: Pipeline Tests;

on: 
 push:
   branches:
     - master
     - branches
jobs:
  backend-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Backend -WebSocket Test/Build
        run: docker build -f Dockerfile.Junit .
